<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Phase 0 initial schema for the SEO domain.
 *
 * Creates the six core tables (theme · region · author · content_node ·
 * data_point · redirect), the messenger queue, plus the ERD-mandated CHECK
 * constraints and PL/pgSQL triggers that enforce:
 *
 * - publish gate     : status='live' requires data_count>=5, intro_text, verified author
 * - data_count sync  : verified=true data_points are auto-counted on parent node
 * - parent live      : a child node cannot go live while its parent isn't live
 * - dead cascade     : status='dead' auto-creates a 301 redirect to the closest live ancestor
 */
final class Version20260506043833 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Phase 0: SEO domain schema (theme/region/author/content_node/data_point/redirect) with publish-gate triggers and silo-integrity CHECK constraints';
    }

    public function up(Schema $schema): void
    {
        $this->createDomainTables();
        $this->createMessengerTable();
        $this->addForeignKeys();
        $this->addCheckConstraints();
        $this->addRefreshDataCountTrigger();
        $this->addPublishGateTrigger();
        $this->addParentLiveCheckTrigger();
        $this->addDeadCascadeRedirectTrigger();
    }

    public function down(Schema $schema): void
    {
        $this->dropTriggersAndFunctions();
        $this->dropForeignKeys();
        $this->dropTables();
    }

    private function createDomainTables(): void
    {
        $this->addSql('CREATE TABLE theme (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, depth SMALLINT NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9775E708727ACA70 ON theme (parent_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_theme_parent_slug ON theme (parent_id, slug)');
        $this->addSql("COMMENT ON COLUMN theme.depth IS '0=root, 1=primary, 2=sub'");

        $this->addSql('CREATE TABLE region (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, depth SMALLINT NOT NULL, admin_code VARCHAR(20) DEFAULT NULL, lat NUMERIC(9, 6) DEFAULT NULL, lng NUMERIC(9, 6) DEFAULT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F62F176727ACA70 ON region (parent_id)');
        $this->addSql('CREATE INDEX idx_region_admin_code ON region (admin_code)');
        $this->addSql('CREATE UNIQUE INDEX uniq_region_parent_slug ON region (parent_id, slug)');
        $this->addSql("COMMENT ON COLUMN region.depth IS '0=country, 1=sido, 2=sigungu, 3=dong'");

        $this->addSql('CREATE TABLE author (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(50) NOT NULL, real_name VARCHAR(100) NOT NULL, credentials TEXT DEFAULT NULL, bio TEXT DEFAULT NULL, photo_url VARCHAR(500) DEFAULT NULL, verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BDAFD8C8989D9B62 ON author (slug)');

        $this->addSql('CREATE TABLE content_node (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, data_count INT DEFAULT 0 NOT NULL, intro_text TEXT DEFAULT NULL, body_template VARCHAR(20) DEFAULT NULL, first_published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_review_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, kpi_snapshot JSONB DEFAULT NULL, theme_id INT NOT NULL, region_id INT DEFAULT NULL, author_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_481D058059027487 ON content_node (theme_id)');
        $this->addSql('CREATE INDEX IDX_481D058098260155 ON content_node (region_id)');
        $this->addSql('CREATE INDEX IDX_481D0580F675F31B ON content_node (author_id)');
        $this->addSql('CREATE INDEX idx_content_node_status ON content_node (status)');
        $this->addSql('CREATE INDEX idx_content_node_last_review_at ON content_node (last_review_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_content_node_theme_region ON content_node (theme_id, region_id)');
        $this->addSql("COMMENT ON COLUMN content_node.data_count IS 'auto-managed by trigger; verified=true count'");

        $this->addSql('CREATE TABLE data_point (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, kind VARCHAR(20) NOT NULL, title VARCHAR(200) NOT NULL, value JSONB NOT NULL, source VARCHAR(500) DEFAULT NULL, verified BOOLEAN DEFAULT false NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, node_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F91A3FBB460D9FD7 ON data_point (node_id)');
        $this->addSql('CREATE INDEX idx_data_point_node_kind ON data_point (node_id, kind)');
        $this->addSql('CREATE INDEX idx_data_point_node_verified ON data_point (node_id, verified)');

        $this->addSql('CREATE TABLE redirect (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, http_status INT DEFAULT 301 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, from_node_id INT NOT NULL, to_node_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C30C9E2BC895A222 ON redirect (to_node_id)');
        $this->addSql('CREATE INDEX idx_redirect_from_node ON redirect (from_node_id)');
    }

    private function createMessengerTable(): void
    {
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    private function addForeignKeys(): void
    {
        $this->addSql('ALTER TABLE theme ADD CONSTRAINT FK_9775E708727ACA70 FOREIGN KEY (parent_id) REFERENCES theme (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE region ADD CONSTRAINT FK_F62F176727ACA70 FOREIGN KEY (parent_id) REFERENCES region (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE content_node ADD CONSTRAINT FK_481D058059027487 FOREIGN KEY (theme_id) REFERENCES theme (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE content_node ADD CONSTRAINT FK_481D058098260155 FOREIGN KEY (region_id) REFERENCES region (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE content_node ADD CONSTRAINT FK_481D0580F675F31B FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE data_point ADD CONSTRAINT FK_F91A3FBB460D9FD7 FOREIGN KEY (node_id) REFERENCES content_node (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE redirect ADD CONSTRAINT FK_C30C9E2BC0537C78 FOREIGN KEY (from_node_id) REFERENCES content_node (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE redirect ADD CONSTRAINT FK_C30C9E2BC895A222 FOREIGN KEY (to_node_id) REFERENCES content_node (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    private function addCheckConstraints(): void
    {
        $this->addSql('ALTER TABLE theme ADD CONSTRAINT chk_theme_depth CHECK (depth >= 0 AND depth <= 2)');
        $this->addSql('ALTER TABLE region ADD CONSTRAINT chk_region_depth CHECK (depth >= 0 AND depth <= 3)');
        $this->addSql("ALTER TABLE content_node ADD CONSTRAINT chk_content_node_status CHECK (status IN ('draft','live','noindex','dead'))");
        $this->addSql("ALTER TABLE data_point ADD CONSTRAINT chk_data_point_kind CHECK (kind IN ('quantitative','qualitative','comparison','case','faq'))");
    }

    private function addRefreshDataCountTrigger(): void
    {
        $this->addSql(<<<'SQL'
            CREATE OR REPLACE FUNCTION fn_refresh_data_count() RETURNS TRIGGER AS $$
            BEGIN
                IF TG_OP IN ('INSERT', 'UPDATE') AND NEW.node_id IS NOT NULL THEN
                    UPDATE content_node
                    SET data_count = (
                        SELECT COUNT(*) FROM data_point
                        WHERE node_id = NEW.node_id AND verified = true
                    )
                    WHERE id = NEW.node_id;
                END IF;

                IF TG_OP IN ('UPDATE', 'DELETE') AND OLD.node_id IS NOT NULL
                   AND (TG_OP = 'DELETE' OR OLD.node_id <> NEW.node_id) THEN
                    UPDATE content_node
                    SET data_count = (
                        SELECT COUNT(*) FROM data_point
                        WHERE node_id = OLD.node_id AND verified = true
                    )
                    WHERE id = OLD.node_id;
                END IF;

                RETURN NULL;
            END;
            $$ LANGUAGE plpgsql
        SQL);

        $this->addSql(<<<'SQL'
            CREATE TRIGGER trg_refresh_data_count
            AFTER INSERT OR UPDATE OR DELETE ON data_point
            FOR EACH ROW EXECUTE FUNCTION fn_refresh_data_count()
        SQL);
    }

    private function addPublishGateTrigger(): void
    {
        $this->addSql(<<<'SQL'
            CREATE OR REPLACE FUNCTION fn_publish_gate() RETURNS TRIGGER AS $$
            DECLARE
                author_verified TIMESTAMP;
            BEGIN
                IF NEW.status <> 'live' THEN
                    RETURN NEW;
                END IF;

                IF NEW.data_count < 5 THEN
                    RAISE EXCEPTION 'Publish gate: content_node % requires data_count >= 5 (have %)', NEW.id, NEW.data_count;
                END IF;

                IF NEW.intro_text IS NULL OR LENGTH(TRIM(NEW.intro_text)) = 0 THEN
                    RAISE EXCEPTION 'Publish gate: content_node % requires non-empty intro_text', NEW.id;
                END IF;

                IF NEW.author_id IS NULL THEN
                    RAISE EXCEPTION 'Publish gate: content_node % requires author_id', NEW.id;
                END IF;

                SELECT verified_at INTO author_verified FROM author WHERE id = NEW.author_id;
                IF author_verified IS NULL THEN
                    RAISE EXCEPTION 'Publish gate: content_node % requires verified author (id=%)', NEW.id, NEW.author_id;
                END IF;

                IF NEW.first_published_at IS NULL THEN
                    NEW.first_published_at := NOW();
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql
        SQL);

        $this->addSql(<<<'SQL'
            CREATE TRIGGER trg_publish_gate
            BEFORE INSERT OR UPDATE ON content_node
            FOR EACH ROW EXECUTE FUNCTION fn_publish_gate()
        SQL);
    }

    private function addParentLiveCheckTrigger(): void
    {
        // Parent of a content_node is the node sharing the same theme, sitting one
        // region-tree step closer to the root. Theme hub (region_id IS NULL) is exempt.
        $this->addSql(<<<'SQL'
            CREATE OR REPLACE FUNCTION fn_parent_live_check() RETURNS TRIGGER AS $$
            DECLARE
                parent_region_id INT;
                parent_status VARCHAR(20);
            BEGIN
                IF NEW.status <> 'live' THEN
                    RETURN NEW;
                END IF;

                IF NEW.region_id IS NULL THEN
                    RETURN NEW;
                END IF;

                SELECT parent_id INTO parent_region_id FROM region WHERE id = NEW.region_id;

                IF parent_region_id IS NULL THEN
                    SELECT status INTO parent_status
                    FROM content_node
                    WHERE theme_id = NEW.theme_id AND region_id IS NULL;
                ELSE
                    SELECT status INTO parent_status
                    FROM content_node
                    WHERE theme_id = NEW.theme_id AND region_id = parent_region_id;
                END IF;

                IF parent_status IS NULL THEN
                    RAISE EXCEPTION 'Parent live check: content_node % has no parent node (theme=%, region_parent=%)', NEW.id, NEW.theme_id, parent_region_id;
                END IF;

                IF parent_status <> 'live' THEN
                    RAISE EXCEPTION 'Parent live check: content_node % cannot go live while parent is % (theme=%, region_parent=%)', NEW.id, parent_status, NEW.theme_id, parent_region_id;
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql
        SQL);

        $this->addSql(<<<'SQL'
            CREATE TRIGGER trg_parent_live_check
            BEFORE INSERT OR UPDATE ON content_node
            FOR EACH ROW EXECUTE FUNCTION fn_parent_live_check()
        SQL);
    }

    private function addDeadCascadeRedirectTrigger(): void
    {
        // When a node transitions to dead, register a 301 redirect to the closest
        // live ancestor in the same theme. If none exists, no redirect is created.
        $this->addSql(<<<'SQL'
            CREATE OR REPLACE FUNCTION fn_dead_cascade_redirect() RETURNS TRIGGER AS $$
            DECLARE
                ancestor_region_id INT;
                ancestor_node_id INT;
            BEGIN
                IF NEW.status <> 'dead' OR (TG_OP = 'UPDATE' AND OLD.status = 'dead') THEN
                    RETURN NEW;
                END IF;

                ancestor_region_id := NEW.region_id;

                LOOP
                    IF ancestor_region_id IS NULL THEN
                        SELECT id INTO ancestor_node_id
                        FROM content_node
                        WHERE theme_id = NEW.theme_id
                          AND region_id IS NULL
                          AND status = 'live'
                          AND id <> NEW.id;
                        EXIT;
                    END IF;

                    SELECT parent_id INTO ancestor_region_id FROM region WHERE id = ancestor_region_id;

                    IF ancestor_region_id IS NULL THEN
                        CONTINUE;
                    END IF;

                    SELECT id INTO ancestor_node_id
                    FROM content_node
                    WHERE theme_id = NEW.theme_id
                      AND region_id = ancestor_region_id
                      AND status = 'live'
                      AND id <> NEW.id;

                    EXIT WHEN ancestor_node_id IS NOT NULL;
                END LOOP;

                IF ancestor_node_id IS NOT NULL THEN
                    INSERT INTO redirect (from_node_id, to_node_id, http_status, created_at)
                    VALUES (NEW.id, ancestor_node_id, 301, NOW())
                    ON CONFLICT DO NOTHING;
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql
        SQL);

        $this->addSql(<<<'SQL'
            CREATE TRIGGER trg_dead_cascade_redirect
            AFTER UPDATE OF status ON content_node
            FOR EACH ROW EXECUTE FUNCTION fn_dead_cascade_redirect()
        SQL);
    }

    private function dropTriggersAndFunctions(): void
    {
        $this->addSql('DROP TRIGGER IF EXISTS trg_dead_cascade_redirect ON content_node');
        $this->addSql('DROP FUNCTION IF EXISTS fn_dead_cascade_redirect()');
        $this->addSql('DROP TRIGGER IF EXISTS trg_parent_live_check ON content_node');
        $this->addSql('DROP FUNCTION IF EXISTS fn_parent_live_check()');
        $this->addSql('DROP TRIGGER IF EXISTS trg_publish_gate ON content_node');
        $this->addSql('DROP FUNCTION IF EXISTS fn_publish_gate()');
        $this->addSql('DROP TRIGGER IF EXISTS trg_refresh_data_count ON data_point');
        $this->addSql('DROP FUNCTION IF EXISTS fn_refresh_data_count()');
    }

    private function dropForeignKeys(): void
    {
        $this->addSql('ALTER TABLE content_node DROP CONSTRAINT FK_481D058059027487');
        $this->addSql('ALTER TABLE content_node DROP CONSTRAINT FK_481D058098260155');
        $this->addSql('ALTER TABLE content_node DROP CONSTRAINT FK_481D0580F675F31B');
        $this->addSql('ALTER TABLE data_point DROP CONSTRAINT FK_F91A3FBB460D9FD7');
        $this->addSql('ALTER TABLE redirect DROP CONSTRAINT FK_C30C9E2BC0537C78');
        $this->addSql('ALTER TABLE redirect DROP CONSTRAINT FK_C30C9E2BC895A222');
        $this->addSql('ALTER TABLE region DROP CONSTRAINT FK_F62F176727ACA70');
        $this->addSql('ALTER TABLE theme DROP CONSTRAINT FK_9775E708727ACA70');
    }

    private function dropTables(): void
    {
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('DROP TABLE redirect');
        $this->addSql('DROP TABLE data_point');
        $this->addSql('DROP TABLE content_node');
        $this->addSql('DROP TABLE author');
        $this->addSql('DROP TABLE region');
        $this->addSql('DROP TABLE theme');
    }
}
