<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260506042051 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE author (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(50) NOT NULL, real_name VARCHAR(100) NOT NULL, credentials TEXT DEFAULT NULL, bio TEXT DEFAULT NULL, photo_url VARCHAR(500) DEFAULT NULL, verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BDAFD8C8989D9B62 ON author (slug)');
        $this->addSql('CREATE TABLE content_node (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, data_count INT DEFAULT 0 NOT NULL, intro_text TEXT DEFAULT NULL, body_template VARCHAR(20) DEFAULT NULL, first_published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_review_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, kpi_snapshot JSONB DEFAULT NULL, theme_id INT NOT NULL, region_id INT DEFAULT NULL, author_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_481D058059027487 ON content_node (theme_id)');
        $this->addSql('CREATE INDEX IDX_481D058098260155 ON content_node (region_id)');
        $this->addSql('CREATE INDEX IDX_481D0580F675F31B ON content_node (author_id)');
        $this->addSql('CREATE INDEX idx_content_node_status ON content_node (status)');
        $this->addSql('CREATE INDEX idx_content_node_last_review_at ON content_node (last_review_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_content_node_theme_region ON content_node (theme_id, region_id)');
        $this->addSql('COMMENT ON COLUMN content_node.data_count IS \'auto-managed by trigger; verified=true count\'');
        $this->addSql('CREATE TABLE data_point (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, kind VARCHAR(20) NOT NULL, title VARCHAR(200) NOT NULL, value JSONB NOT NULL, source VARCHAR(500) DEFAULT NULL, verified BOOLEAN DEFAULT false NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, node_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F91A3FBB460D9FD7 ON data_point (node_id)');
        $this->addSql('CREATE INDEX idx_data_point_node_kind ON data_point (node_id, kind)');
        $this->addSql('CREATE INDEX idx_data_point_node_verified ON data_point (node_id, verified)');
        $this->addSql('CREATE TABLE redirect (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, http_status INT DEFAULT 301 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, from_node_id INT NOT NULL, to_node_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C30C9E2BC895A222 ON redirect (to_node_id)');
        $this->addSql('CREATE INDEX idx_redirect_from_node ON redirect (from_node_id)');
        $this->addSql('CREATE TABLE region (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, depth SMALLINT NOT NULL, admin_code VARCHAR(20) DEFAULT NULL, lat NUMERIC(9, 6) DEFAULT NULL, lng NUMERIC(9, 6) DEFAULT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F62F176727ACA70 ON region (parent_id)');
        $this->addSql('CREATE INDEX idx_region_admin_code ON region (admin_code)');
        $this->addSql('CREATE UNIQUE INDEX uniq_region_parent_slug ON region (parent_id, slug)');
        $this->addSql('COMMENT ON COLUMN region.depth IS \'0=country, 1=sido, 2=sigungu, 3=dong\'');
        $this->addSql('CREATE TABLE theme (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, depth SMALLINT NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9775E708727ACA70 ON theme (parent_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_theme_parent_slug ON theme (parent_id, slug)');
        $this->addSql('COMMENT ON COLUMN theme.depth IS \'0=root, 1=primary, 2=sub\'');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE content_node ADD CONSTRAINT FK_481D058059027487 FOREIGN KEY (theme_id) REFERENCES theme (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE content_node ADD CONSTRAINT FK_481D058098260155 FOREIGN KEY (region_id) REFERENCES region (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE content_node ADD CONSTRAINT FK_481D0580F675F31B FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE data_point ADD CONSTRAINT FK_F91A3FBB460D9FD7 FOREIGN KEY (node_id) REFERENCES content_node (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE redirect ADD CONSTRAINT FK_C30C9E2BC0537C78 FOREIGN KEY (from_node_id) REFERENCES content_node (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE redirect ADD CONSTRAINT FK_C30C9E2BC895A222 FOREIGN KEY (to_node_id) REFERENCES content_node (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE region ADD CONSTRAINT FK_F62F176727ACA70 FOREIGN KEY (parent_id) REFERENCES region (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE theme ADD CONSTRAINT FK_9775E708727ACA70 FOREIGN KEY (parent_id) REFERENCES theme (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE content_node DROP CONSTRAINT FK_481D058059027487');
        $this->addSql('ALTER TABLE content_node DROP CONSTRAINT FK_481D058098260155');
        $this->addSql('ALTER TABLE content_node DROP CONSTRAINT FK_481D0580F675F31B');
        $this->addSql('ALTER TABLE data_point DROP CONSTRAINT FK_F91A3FBB460D9FD7');
        $this->addSql('ALTER TABLE redirect DROP CONSTRAINT FK_C30C9E2BC0537C78');
        $this->addSql('ALTER TABLE redirect DROP CONSTRAINT FK_C30C9E2BC895A222');
        $this->addSql('ALTER TABLE region DROP CONSTRAINT FK_F62F176727ACA70');
        $this->addSql('ALTER TABLE theme DROP CONSTRAINT FK_9775E708727ACA70');
        $this->addSql('DROP TABLE author');
        $this->addSql('DROP TABLE content_node');
        $this->addSql('DROP TABLE data_point');
        $this->addSql('DROP TABLE redirect');
        $this->addSql('DROP TABLE region');
        $this->addSql('DROP TABLE theme');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
